gsk-aiops/bellman

- src/main/scala/Expr.scala
- src/main/scala/ExprParser.scala
- src/main/scala/FilterFunction.scala
- src/main/scala/FilterFunctionParser.scala
- src/main/scala/StringFuncParser.scala
- src/main/scala/StringLike.scala
- src/main/scala/StringValParser.scala
- src/test/scala/ExprParserSpec.scala
- src/test/scala/FilterFunctionParserSpec.scala
- src/test/scala/StringFuncParserSpec.scala
Moved ADTs into objects to clean up default namespace.
> Refactor adt

- scalastyle-config.xml
Scalastyle warnings will now result in an error and should block merging until resolved.
> Converted scalastyle warnings to errors

- build.sbt
- scalastyle-config.xml
- src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala
- src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala
- src/test/scala/com/gsk/kg/sparqlparser/FilterFunctionParserSpec.scala
- src/test/scala/com/gsk/kg/sparqlparser/QueryConstructSpec.scala
- src/test/scala/com/gsk/kg/sparqlparser/StringFuncParserSpec.scala
- src/test/scala/com/gsk/kg/sparqlparser/TestUtils.scala
Moved tests into gsk.kg.sparqlparser namespace. Also testing scalastyle fail on warning.
> Update test namespace

- README.md
This PR adds some more info to the README
> add more information to the README

- modules/parser/src/main/scala/com/gsk/kg/sparql/Visitors.scala
- modules/parser/src/main/scala/com/gsk/kg/sparql/impl/ExprToText.scala
- modules/parser/src/main/scala/com/gsk/kg/sparql/impl/SimpleVisitor.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/FilterFunction.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/FilterFunctionParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringLike.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringValParser.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamples.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamplesTestSpec.scala
add limit and offset query support in parser.
add distinct query support.
add function isBlank and negate (!) support.
> add query samples and parser tests.

- build.sbt
> spark 2.4.7 -> 2.4.0

- build.sbt
- modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/syntax/SyntaxSpec.scala
> Reformat resulting DataFrame as per RDF

- modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala
This PR fix a bug that formatted all data typed literals with extra double quotes.
Closes #101 #102
> fixed quotation on data typed literals

- build.sbt
- modules/engine/src/test/scala-2.11/com/gsk/kg/engine/DataFrameGeneratorSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CommonGenerators.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/DataFrameGenerator.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala
> add a way of generating random DataFrames

- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
Filter over select statements is already supported, so this PR only adds one more test and un-ignore another test.
Merge after #88 
Closes #115
> Sparql filter over select statement

- modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
This PR add support for SparQL DISCTINCT statement.
It discards duplicated solutions on the query result.
> added support for disctinct

- modules/engine/src/main/scala/com/gsk/kg/engine/optimize/Optimizer.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/optimize/RemoveNestedProject.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/optimize/RemoveNestedProjectSpec.scala
This optimization will deduplicate Project nodes in the DAG
Closes #138
> introduce RemoveNestedProject optimization

- modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala
This PR fixes the double quotation on strings when formatting RDF.
Closes #148 
Merge After #147
> Fix double qoutation string

- build.sbt
- modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/CommonGenerators.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala
This PR introduces the ability to use binary operators on xsd:dateTime values.
~I still need to work through some binary dependency issues with Spark in the CompilerSpec before turning it into a _real_ PR :)~
Closes #136
> make it possible to apply binary operators on dates

- modules/engine/src/main/scala/com/gsk/kg/engine/data/ChunkedList.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/optimize/CompactBGPsSpec.scala
Fix triple ordering issue caused by `CompactBGPs` step
> fix-compact-bgp-ordering-issue

- modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/Analyzer.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/package.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/analyzer/AnalyzerSpec.scala
This PR replaces the StateT monad for ReadWriteStateT monad, this way we can pass a dependency through all compiler phases, it also allows to add a Log.
Closes #220
> replaced StateT monad for ReadWriteStateT monad

- modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
This PR add a flag to strip question marks on columns for Spark DataFrame output.
Closes #195
> added strip question marks on ouput

- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
Fixing scala doc error.  re: https://github.com/scala/bug/issues/11986
> Support for strstarts

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
This PR adds the REGEX function without flags.  It also removes doc tables that are causing the CI job to fail.
Closes #128
> Support for regex function without flags

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala
This PR adds support for calling the SPARQL function REGEX with flags.
Closes #253
> Support for regex with flags

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamplesTestSpec.scala
This PR adds support for calling the SPARQL function REPLACE with flags.
Closes #98
> Add support for REPLACE function with flags

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/ExpressionArbitraries.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
This PR adds support for calling the SPARQL function STRENDS.
Closes #268
> Support for strends

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/ExpressionArbitraries.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
This PR adds support for the SparQL SUBSTR function.
Closes #271
> Add support for SUBSTR function

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
This PR add support for function STRDT.
https://www.w3.org/TR/sparql11-query/#func-strdt
Closes #264
> Add support strdt

- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrdtSpec.scala
This PR adds test coverage for STRDT on SELECT statement.
Closes #264
> added test for select statement

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrafterSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/data/TreeRepSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringValParser.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ShortQueryTestSpec.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/StringValParserSpec.scala
This PR adds test coverage to STRAFTER on edge cases, specially on typed and localized strings.
It also sets a way to add same tests to other string functions as STRBEFORE, STRSTARTS, STREND and CONTAINS.
Closes #340
> Add coverage strafter

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrlenSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
This PR adds support for STRLEN function on strings.
Closes #270
> Add support strlen

- .scala-steward.conf
- build.sbt
Make scala-steward ignore spark updates
> scala-steward: ignore updates to spark

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/IsNumericSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/ExpressionArbitraries.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
This PR adds support for the isNumeric SPARQL function.
Closes #170
> Support for isnumeric

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/LangSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/ExpressionArbitraries.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
This PR implements the SparQL function LANG.
Closes #262
> Implement lang

- modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/GroupBySpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/DAGArbitraries.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala
This PR makes it possible to use more than one aggregation in a single query.  I've needed to change Group in both parsing AST and the DAG, and changed the mapping to Spark operations too.
Closes #382
> Multiple aggregations

- modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/AskSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/ExpressionArbitraries.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
This PR adds support for ASK queries: E.g:
```
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
ASK  { ?x foaf:name  "Alice" }
```
It also fixes a issue on BGP's conditions that could cause unexpected results on some queries. 
Closes #245
> Add support ask

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncForms.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/IfSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncFormsSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/DAGArbitraries.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/ExpressionArbitraries.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ConditionalParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ConditionalParserSpec.scala
- scalastyle-config.xml
This PR adds support for IF function. E.g:
```
SELECT ?name ?cat
WHERE {
?s foaf:name ?name .
?s foaf:age ?age .
BIND(IF(?age < 18, "child", "adult") AS ?cat)
}
```
It also implements a function for [Effective Boolean Value](https://www.w3.org/TR/sparql11-query/#ebv).
Closes #257
> Add support if

- modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncForms.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/BGPSpec.scala
This PR fixes BGP matching on literals:
- String literals
- Boolean literals
> Fix literals return no results

- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/QueryExtractorSpec.scala
Fix errors when cleaning the query off of queryparams in graph urls
> reimplement queryextractor using Jena's sse

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/UUIDSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncTermsSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Add uuid support function according specification, https://www.w3.org/TR/sparql11-query/#func-uuid
> Add UUID function

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncArithmetics.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ArithmeticSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ArithmeticParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExpressionParser.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ArithmeticParserSpec.scala
- scalastyle-config.xml
This PR add support for arithmetic functions: +, -, *, /
See related: #439
Closes #427
> Add support arithmetic funcs

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Ceilspec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncNumericsSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Add ceil function according the specification: https://www.w3.org/TR/sparql11-query/#func-ceil
> Add ceil function

- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncAgg.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncArithmetics.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncForms.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Ceilspec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncArithmeticSpec.scala
Thus PR adds type promotion on typed arguments of arithmetic operations: +, -, *, /
Closes #439
> added type promotion to arithmetic operations

- modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/EqualsSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncFormsSpec.scala
This PR fixes some issues when equals on plain strings that not match when extra double quoted.
> fixed equals on plain string literals

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/RoundSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncNumericsSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Add round function according the specification: https://www.w3.org/TR/sparql11-query/#func-round
> Add round function

- .github/workflows/rdf-tests.yml
- build.sbt
previously, RDF-tests were not compiling
> make rdf-tests rely on test artifacts

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/RandSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncNumericsSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Adding rand function according to specification
https://www.w3.org/TR/sparql11-query/#idp2130040
> Add rand function

- modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/SubqueryPushdown.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/PropertyExpression.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/PropertyPathParser.scala
- modules/parser/src/test/resources/queries/q50-property-simple-alt.sparql
- modules/parser/src/test/resources/queries/q51-property-simple-rev.sparql
- modules/parser/src/test/resources/queries/q52-property-simple-seq.sparql
- modules/parser/src/test/resources/queries/q53-property-simple-plus.sparql
- modules/parser/src/test/resources/queries/q54-property-simple-star.sparql
- modules/parser/src/test/resources/queries/q55-property-simple-question.sparql
- modules/parser/src/test/resources/queries/q56-property-simple-negation.sparql
- modules/parser/src/test/resources/queries/q57-property-simple-nm.sparql
- modules/parser/src/test/resources/queries/q58-property-simple-n.sparql
- modules/parser/src/test/resources/queries/q59-property-simple-ncomma.sparql
- modules/parser/src/test/resources/queries/q60-property-simple-comman.sparql
- modules/parser/src/test/resources/queries/q61-property-complex-1.sparql
- modules/parser/src/test/resources/queries/q62-property-complex-2.sparql
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/PropertyExpressionParserSpec.scala
- modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
WIP: This PR adds support for path properties on parser side.
> Path properties algebra

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/YearSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Add year function according specification:
https://www.w3.org/TR/sparql11-query/#func-year
> year function impl

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/MonthSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
add month function according specification
https://www.w3.org/TR/sparql11-query/#func-month
> Add month function

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/DaySpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/MonthSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
add day function according specification
https://www.w3.org/TR/sparql11-query/#func-day
> Add day function

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/HoursSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/SparkSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Add hours function according specitication
https://www.w3.org/TR/sparql11-query/#func-hours
> add hours function

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/MinutesSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Add minutes functions according specification:
https://www.w3.org/TR/sparql11-query/#func-minutes
> Add minutes function

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/TimezoneSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Add timezone function according specification:
https://www.w3.org/TR/sparql11-query/#func-timezone
> timezone function implementation

- modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/TzSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
- modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Add tz function according specification
https://www.w3.org/TR/sparql11-query/#func-tz
> Add tz function

- modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/package.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
This PR adds support for one or more length property path. E.g:
```
SELECT ?s ?o
WHERE {
?s foaf:knows+ ?o .
}
```
> add support one or more property path (+)

- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/CompilerSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/InclusiveGraphsSpec.scala
- modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala
This PR fixes a bug where the behaviour when explicitly constructed the dataset with FROM was being inclusive instead of exclusive.
> fixed default graph when dataset explicitly constructed

- modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
This PR adds support for exactly n path. E.g:
```
SELECT ?s ?o
WHERE {
?s foaf:knows{2} ?o .
}
```
> Property path exactly n

- modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
This PR add support for between n and m property path. E.g:
```
SELECT ?s ?o
WHERE {
?s foaf:knows{1, 3} ?o .
}
```
Merge after #497
> Property path between n m

- modules/engine/src/main/scala/com/gsk/kg/engine/DataFrameTyper.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/syntax/package.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/Promotion.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/TypedFuncForms.scala
- modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/TypedLiterals.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/TypedFuncFormsSpec.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/TypedLiteralsSpec.scala
This PR adds typed versions for all functions under Literals.scala and FuncForms.scala, two of the most depedned upon utilities in Sparql functions.
> type Funcforms and Literals

- modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/FuncNumerics.scala
- modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/FuncNumericsSpec.scala
Implement typed version of FuncNumerics
> first version of FuncNumerics
