gsk-aiops/bellman

build.sbt
When moving things to `Versions`, I think y broke cross-compiling.  This PR restores it :)
=> fix crossScalaVersions

modules/parser/src/main/scala/com/gsk/kg/sparql/Visitors.scala, modules/parser/src/main/scala/com/gsk/kg/sparql/impl/ExprToText.scala, modules/parser/src/main/scala/com/gsk/kg/sparql/impl/SimpleVisitor.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/FilterFunction.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/FilterFunctionParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringFuncParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringLike.scala, modules/parser/src/test/scala/com/gsk/kg/sparql/impl/SimpleVisitorSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QueryConstructSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamplesTestSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/TestUtils.scala
Factor out Query types (Construct, Select, Describe, Ask) from Expr
Change Select in Expr to Project
Make FilterFunction and StringLike all are Expression trait
add support of ||, && binary expressions
add support of replace function
Two of sample queries failed to parse, put under ignore and will fix them later.
=> Sparql parser tests on sample queries

build.sbt, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Predicate.scala, modules/engine/src/test/scala/com/gsk/kg/engine/EngineSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/MultisetSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringLike.scala
This PR introduces the basic structure for the Spark engine.100%
first of all, I've need to juggle with dependencies a bit to make both
Jena and Spark coexist in the project.  Jena uses a newer version of
JAckson, while spark uses an old one.  I needed to downgrade Jena's.
The entry point for the project is the `Engine` object.  It contains
the evaluate method that will receive an `Expr`, a `DataFrame`, and
will apply the SparQL algebra expression tothe DF.100%
So far, only `SELECT` with Basic Graph Patterns are supported.  I
still have to add some more tests to it to check that the semantics
are correct.
The other central piece for the engine is the `Multiset` datatype.
I've modeled BGP & Select semantics described on
https://www.w3.org/2001/sw/DataAccess/rq23/rq24-algebra.html directly …
=> Create basic structure for the spark Engine

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/test/scala/com/gsk/kg/engine/EngineSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/MultisetSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparql/syntax/Interpolators.scala, modules/parser/src/main/scala/com/gsk/kg/sparql/syntax/all.scala
This PR makes it possible to evaluate union queries.
We rely on Spark DataSet's `union` functions, and depending on the
shared bindings of the different multisets we keep the same DF
structure, or add the needed columns.
I also introduced some syntax sugar for making it possible to parse
sparql queries directly, using the `sparql` interpolator.
``` scala
val query: Query = sparql"""
SELECT {?s ?p ?o}
WHERE {?s ?p ?o}
"""
```
Under the hood, it just calls `QueryConstruct.parse`.
=> Evaluate union queries

build.sbt, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/EngineError.scala, modules/engine/src/main/scala/com/gsk/kg/engine/QueryExecutor.scala, modules/engine/src/test/scala/com/gsk/kg/engine/EngineSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala
This PR adds support for CONSTRUCT queries.
I've ignored one of the tests, because I need to still work on it, since the result it's returning is not what I expect.
https://github.com/gsk-aiops/bellman/compare/construct-support?expand=1#diff-00cff14d890e1d2c20ecd6793ff453d1d856242c402fa1d5e58720eadc9f7bb1R131-R186
What the engine is returning is each row duplicated.  By reading the spec, I feel that CONSTRUCT query results shouldn't have duplicated, since it explicitly talks about `set union`, not `multiset union`, and we could safely remove duplicates from result, but am not completely sure.
If you @shihch @JNKHunter know how should we proceed in that regard I'd really appreciate that.
=> Construct support

modules/engine/src/main/scala/com/gsk/kg/engine/syntax/package.scala, modules/engine/src/test/scala/com/gsk/kg/engine/syntax/SyntaxSpec.scala
Make it possible to query a dataframe directly adding an extension method `sparql`.
``` scala
import com.gsk.kg.engine.syntax._
val df: DataFrame = ???
df.sparql("SELECT {?s ?p ?o} WHERE {?s ?p ?o}")
```
=> add sparql syntax on dataframe

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/EngineError.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
This PR adds SparQL Solution Sequence Modifier LIMIT support.
Acceptance criteria:
If LIMIT greater than 0, will return a maximum of LIMIT elements.
If LIMIT equals 0, will return no elements.
If LIMIT less than 0, an Engine Error will happen.
If LIMIT is greater than Java MAX_INTEGER, an Engine Error will happen. (Due to Spark limit type Int)
WIP: Offset support
CLOSES: #73
=> added limit operation support for sparql queries on compiler

modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/EngineError.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
This PR separates the two different constructs in the DAG.  We don't really need them to be tied together.  Also, in the transformation, we're checking in case both are None, in which case we pass the underlying algebra directly.
To be merged after #74
=> Split offset and limit

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/EngineError.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
This PR adds SparQL Solution Sequence Modifier OFFSET support.
Acceptance criteria:
Given a sequence of solutions S = (S0, S1, ..., Sn) where N is the total number of solutions without modifier.
Then Offset(S, K) where K is the offset:
- If K >= 0 and N >= K it will return S' where S' = S(Sk, Sk+1, ..., Sn)
- If K >= 0 and N < K it will return S' where S' = ()
- If K == 0 it will return S' where S' = S
- If K < 0 it will return an Engine Error
Merge after #75
=> Sparql offset support

modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/TreeRep.scala
This PR parametrizes ToTree[A] so the nodes of the tree now can hold an A type. 
With this we can draw more generic tree representations when provided an evidence of typeclass Show on A when draw method is called.
=> added show typeclass to TreeRep draw method

modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
This PR adds SparQL isBlank function support to the engine.
Returns true if term is a blank node. Returns false otherwise.
Closes #86
=> added support for sparql function isBlank

modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
This PR add SparQL FILTER support.
It restricts the solution of a graph according to a given constraint. This is done by eliminate any solutions that, when evaluated  into the expression, either result in an effective boolean value of false or produce an error.
Closes #83
=> added sparql filter expression support

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
This PR adds SparQL support for OPTIONAL operation. It performs a left outer join in Spark and also applies, in case they exist, filters on the right side of the join.
Closes #87
=> added sparql optional support

modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
This PR adds support for !isBlank, it also adds support for any query expression that is parsed by the engine as a NOT operation in our DAG.
Closes #88
=> added support for negated isBlank

modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala, modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ConditionalParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ConditionalParserSpec.scala, scalastyle-config.xml
This PR add support for the next binary logical operations on SparQL queries based on the next spec: https://www.w3.org/TR/rdf-sparql-query/#OperatorMapping
* `&&` -> For booleans
* `||` -> For booleans
* `=` -> For strings, numbers and booleans. TODO: String literals, dates
* `!=` -> For strings, numbers and booleans, TODO: String literals, dates
* `>` -> For strings, numbers and booleans, TODO: String literals, dates
* `<` -> For strings, numbers and booleans, TODO: String literals, dates
* `>=` -> For strings, numbers and booleans, TODO: String literals, dates
* `<=` -> For strings, numbers and booleans, TODO: String literals, dates
Also it refactors CompilerSpec test structure with AnyWordSpec.
Closes #118 
Closes #119
=> added support for logical operations

modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QueryConstructSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamples.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamplesTestSpec.scala
This PR add support for parsing queries that contains:
* `FROM` for default graphs
* `FROM NAMED` for named graphs
* `GRAPH` on where clause with URI and with variable
The default and named graphs URIs are passed as List of URIs to the engine through the `Construct`, `Select`, `Ask` and `Describe` expressions.
The graph to query (URI or VARIABLE) on `where` statement is passed to the engine through the Graph expression. 
Closes #130
Closes #131
=> added support for default and named graph on parser side

modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala, modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala
Identify correctly localized strings so that they get formatted without extra quotes surrounding them.
Closes #134
=> format localized strings correctly

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/MultisetSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/utils/MultisetMatchers.scala
This PR add support for joining two graphs. Example:
```
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ex: <http://example.org/>
SELECT ?x ?mbox
FROM <http://example.org/dft.ttl>
FROM NAMED <http://example.org/alice>
FROM NAMED <http://example.org/bob>
WHERE
{
GRAPH ex:alice { ?x foaf:mbox ?mbox . }
GRAPH ex:bob { ?x foaf:mbox ?mbox . }
}
```
It also adds some missing test on `Multiset` operations.
=> sparql support for graph joins

build.sbt
- avoid warning on unused code in the console
- add initial commands that initialize Spark
=> Make the console more usable

.scalafix.conf, build.sbt, modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/analyzer/AnalyzerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/data/TreeRepSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/CompactBGPsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/GraphsPushdownSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/RemoveNestedProjectSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparql/syntax/Interpolators.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QueryConstructSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamplesTestSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ShortQueryTestSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/TestUtils.scala
This PR sets the behavior of the engine as inclusive for default graphs and also allows to change and test exclusive behavior easily.
In the future it can be retrieved from some type of configuration.
Closes #200
=> Added support for inclusive/exclusive default graph with inclusive as default value

modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimize/GraphsPushdown.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimize/Optimizer.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/MultisetSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/GraphsPushdownSpec.scala, modules/parser/src/main/scala/com/gsk/kg/Graphs.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamplesTestSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/TestUtils.scala
This PR adds support for use of variables in GRAPH statement. Eg:
```
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ex: <http://example.org/>
SELECT ?who ?g ?mbox
FROM <http://example.org/dft.ttl>
FROM NAMED <http://example.org/alice>
FROM NAMED <http://example.org/bob>
FROM NAMED <http://example.org/charles>
WHERE
{
?g dc:publisher ?who .
GRAPH ?g { ?x foaf:mbox ?mbox }
}
```
Closes #173
=> added support for variables on graph statement

.scalafix.conf, build.sbt, modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala, modules/engine/src/main/scala/com/gsk/kg/engine/syntax/package.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/analyzer/AnalyzerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/data/TreeRepSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/CompactBGPsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/GraphsPushdownSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/RemoveNestedProjectSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/syntax/SyntaxSpec.scala, modules/parser/src/main/resources/application.conf, modules/parser/src/main/scala/com/gsk/kg/config/Config.scala, modules/parser/src/main/scala/com/gsk/kg/sparql/syntax/Interpolators.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QueryConstructSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamplesTestSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ShortQueryTestSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/TestConfig.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/TestUtils.scala
This PR enables to pass a configuration to the compiler.
It makes use of [pureconfig](https://pureconfig.github.io/), so configuration can be read from HOCON file, Json file, build properties file and also from JVM options passed on startup.
Also it sets the default behaviour of the engine to be `exclusive`.
Closes #210
=> Engine configuration

modules/engine/src/main/scala/com/gsk/kg/engine/syntax/package.scala, modules/engine/src/test/scala/com/gsk/kg/engine/syntax/SyntaxSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparql/syntax/Interpolators.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/InterpolatorsSpec.scala
This PR fixes:
- Query parse interpolator `sparql`, that now uses a default configuration. If a custom configuration what to be provided `QueryConstruct.parse` should be used instead.
- Dataframe `sparql` method. Now we have two methods one with default configuration and one with provided configuration, so we have backward compatibility.
Closes #218 
Closes #225
=> fixed query interpolator and dataframe sparql method

build.sbt, modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/Analyzer.scala, modules/engine/src/main/scala/com/gsk/kg/engine/package.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/MultisetSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/analyzer/AnalyzerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/data/TreeRepSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/CompactBGPsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/GraphsPushdownSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/RemoveNestedProjectSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/optimize/SubqueryPushdownSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparql/syntax/Interpolators.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/EngineError.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ParserError.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/package.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QueryConstructSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamplesTestSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ShortQueryTestSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/TestUtils.scala, modules/site/src/main/scala/com/gsk/kg/site/Animations.scala, modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
This PR wraps the engine method `QueryConstruct.parse` into a `Result` monad so it can be managed as the rest of the phases of the Engine. 
Now, Jena exceptions are captured into the left projection of `Result` so errors can be handled in an homogeneous way through all the engine.
Closes #231
=> wrapped parser into engine Result monad

modules/site/src/main/docs/configuration.md, modules/site/src/main/resources/microsite/data/menu.yml
This PR adds some documentation about configuration flags to the Bellman's microsite.
Closes #236
=> added configuration documentation

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala
This PR adds support for strings on MIN and MAX aggregate functions. Out put has been contrasted with Apache Jena.
Closes #232
=> added support for string on aggregates MIN and MAX

modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/SubqueryPushdown.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/OrderConditionParser.scala, modules/parser/src/test/resources/queries/q41-orderby-simple-variable.sparql, modules/parser/src/test/resources/queries/q42-orderby-simple-condition.sparql, modules/parser/src/test/resources/queries/q43-orderby-multi-mixing.sparql, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/OrderConditionParserSpec.scala, modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
This PR add support for queries with order by like this one:
```
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
SELECT ?name
WHERE { ?x foaf:name ?name ; foaf:age ?age }
ORDER BY DESC(?name) ?age DESC(?age) ASC(?name) DESC((isBlank(?x) || isBlank(?age)))
```
Where variables, functions and binary operations can be defined as conditions.
Closes #89
=> Support for order by

modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/analyzer/AnalyzerSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
This PR adds static analysis support for unbounded variables on GROUP BY, ORDER BY and FILTER. 
When some variables on statement conditions are not defined in the WHERE or BGPs clauses, then it fails with an error.
Closes #313
=> Add expression variables to find unbounded

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ConstructSpec.scala
Avoid calling orderby on all constructs.  This will avoid performance bottlenecks, and the user can still orderby if they want by specifying it on the query
Closes to #333
=> don't orderBy by default

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ConstructSpec.scala
This PR eliminates duplicate BGPs from CONSTRUCT queries.
This is congruent with Apache Jena that they also remove duplicates.
Closes #321
=> remove duplicates from Construct

modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala, modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala
Since uris didn't need to contain angle brackets before, this function
was just a simple identity.  Now we're actually checking if the
received value is a angle bracket wrapped uri, or if it's a string
that needs to be wrapped.
Closes #337
=> fix uri function

modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ConstructSpec.scala
This PR un-ignores test on CONSTRUCT suite, that checks for no duplicates when input dataframe contains duplicates.
=> un-ignore test where duplicated data on construct

modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/test/scala/com/gsk/kg/engine/analyzer/AnalyzerSpec.scala
In this PR I needed to change the implementation of FindUnboundVariables.  the reason for that is that previously we were using a State monad for containing the declared vars, but that's not correct.  It's not correct because a piece of a query `a` may declare a variable and put it in the state, and a piece `b` may find it there, even if `b` shouldn't find that var in their lexical scope.
The approach we're following now is to have a simple cata that carries two values in a tuple, the declared variables, and the unbound variables.
closes #234
=> make FindUnboundVariables find unbound vars in nested queries

modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/LangMatchesSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/ExpressionArbitraries.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala, scalastyle-config.xml
This PR implements the SparQL function langMatches.  It uses the Java Locale package.
Closes #275
=> Support for langmatches

.gitignore, modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/SubqueryPushdown.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ValuesSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringValParser.scala, modules/parser/src/test/resources/queries/q44-values-simple-variable.sparql, modules/parser/src/test/resources/queries/q45-values-multiple-variables.sparql, modules/parser/src/test/resources/queries/q46-values-multiple-values-rows.sparql, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala
This PR adds support for VALUES statement on queries that allows to set inline data.
I does not support UNDEF on VALUES table. See https://github.com/gsk-aiops/bellman/issues/390
Closes #227
=> Add support values with no undef on table

modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Func.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/test/scala/com/gsk/kg/engine/FuncSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Md5Spec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Sha1Spec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Sha256Spec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Sha384Spec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Sha512Spec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/ExpressionArbitraries.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala, scalastyle-config.xml
This PR implements the SparQL hashing functions MD5, SHA1, SHA256, SHA384, and SHA512.
Closes #290
Closes #291 
Closes #292 
Closes #293 
Closes #294
=> Implement hashing functions

modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncForms.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/InSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncFormsSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ConditionalParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ConditionalParserSpec.scala
This PR adds support for IN/NOT IN function. E.g:
```
SELECT ?title
WHERE {
?film foaf:title ?title .
FILTER (lang(?title) NOT IN ("en", "es"))
}
```
Closes #261
=> Add support in/not in

modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncForms.scala, modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncStrings.scala, modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala, modules/engine/src/test/scala/com/gsk/kg/engine/MultisetSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/SameTermSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncFormsSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ConditionalParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ConditionalParserSpec.scala, modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
This PR adds support for SAMETERM function. E.g:
```
SELECT ?name1 ?name2
WHERE { 
?x foaf:name  ?name1 ;
foaf:mbox  ?mbox1 .
?y foaf:name  ?name2 ;
foaf:mbox  ?mbox2 .
FILTER (sameTerm(?mbox1, ?mbox2) && !sameTerm(?name1, ?name2))
} 
```
It also correct a bug that was causing failing some queries when some join conditions. See: https://github.com/gsk-aiops/bellman/issues/357
Closes #259 
Closes #357
=> Add support sameterm

modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala, modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala
This PR fixes quotation when plain literals are already quoted so extra double quotes won't be added.
Closes #393
=> fixed quotation on plain literal already quotated

modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala, modules/engine/src/test/scala/com/gsk/kg/engine/QueryExtractorSpec.scala
This PR introduces a new QueryExtractor object.
`QueryExtractor` has a `extractInfo` method that receives a query as a string and returns a tuple with a map of all query params related to their respective graph URIs, and a _clean_ query.  The _clean_ query has all the graph URIs stripped from query parameters.
Closes AIPL-3209
=> Query extractor

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ConstructSpec.scala
This PR fixes errores when CONSTRUCT query with subquery returning dataframe with non String type columns due to aggregate functions. E.g:
```
CONSTRUCT {
?s foaf:knowsN ?nPeople .
?s foaf:minAge ?minAge
} WHERE {
SELECT ?s (COUNT(?people) AS ?nPeople) (MIN(?age) AS ?minAge)
WHERE {
{ ?s foaf:knows ?people }
UNION
{ ?s foaf:age ?age }
}
GROUP BY ?s
}
```
Closes #406
=> Fix construct on numeric literals

modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/SubqueryPushdown.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ReducedSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala, modules/parser/src/test/resources/queries/q49-reduced-simple-query.sparql, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala, modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
This PR add support for REDUCED solutions modifier. E.g:
```
SELECT REDUCED ?name
WHERE { ?x foaf:name ?name }
```
Note: It has been implemented as distinct as it is up to the Sparql endpoint whether to eliminate duplicates or not.
See: https://www.w3.org/TR/sparql11-query/#modReduced
Closes #295
Merge after #424 
Merge after #425
=> Add support reduced modifier

modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Ceilspec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncNumericsSpec.scala
The ceil, round, ... functions must process these data types: xs:float, xs:double, xs:decimal and xs:integer
=> Add support for numeric types

modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
if using `cancel()` in rdf tests, we get too many false positives.  Let's change that with `fail()`
=> fix rdf-test to get more accuracy in reports

.github/workflows/scala.yml, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Bug3255Spec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/SparkSpec.scala
this PR modifies the default shuffle partitions for spark, which in local environments can help with performance
=> constrain the number off shuffle partitions to 1 in test

modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/SubqueryPushdown.scala, modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/EngineError.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/PropertyExpression.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/PropertyPathParser.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/PropertyExpressionParserSpec.scala, modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
This PR adds support for alternative property path. E.g:
```
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?book ?displayString
WHERE {
?book dc:title|rdfs:label ?displayString .
}
```
=> add support for alternative property path

modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringValParser.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/StringValParserSpec.scala
This PR fixes AIPL-3429, using the strict `~~` fastparse combinator so we're able to capture whitespace within the string
=> use strict non-whitespace combinator to capture whitespace inside

build.sbt, modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/EngineError.scala
This PR adds support for `seq` property path. E.g:
```
SELECT ?o
WHERE {
?s foaf:knows/foaf:knows/foaf:name ?o .
}
```
=> added implementation for seq property path

modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
This PR adds support for zero or more property path. E.g:
```
SELECT ?s ?o
WHERE {
?s foaf:knows* ?o .
}
```
Merge after #485
=> add support zero or more property path (*)

modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala, modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala, modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala, modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala, modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncTermsSpec.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala, modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala, modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
Implementation of the datatype function.
```
iri  DATATYPE (literal literal)
Returns the datatype IRI of a literal.
If the literal is a typed literal, return the datatype IRI.
If the literal is a simple literal, return xsd:string
If the literal is literal with a language tag, return rdf:langString
```
More at https://www.w3.org/TR/sparql11-query/#func-datatype
Closes #263
=> Add datatype function

modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
This PR adds support for zero or one property path (optional). E.g:
```
SELECT ?s ?o
WHERE {
?s foaf:knows? ?o .
}
```
Merge after #487
=> add support property path zero or one

modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
This PR adds support for two property paths:
- N or More paths:
```
SELECT ?s ?o
WHERE {
?s foaf:knows{2,} ?o .
}
```
- Zero to N paths:
```
SELECT ?s ?o
WHERE {
?s foaf:knows{,2} ?o .
}
```
Merge after #502
=> Property paths n or more and zero to n

modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala, modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
This PR adds support for NotOneOf property path. E.g:
```
SELECT ?s ?o
WHERE {
?s !foaf:knows ?o .
}
```
=> added support for not one of property path

build.sbt, modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala, modules/engine/src/main/scala/com/gsk/kg/engine/DataFrameTyper.scala, modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala, modules/engine/src/test/scala/com/gsk/kg/engine/DataFrameTyperTest.scala, modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala, modules/parser/src/main/resources/application.conf, modules/parser/src/main/scala/com/gsk/kg/config/Config.scala, modules/parser/src/test/scala/com/gsk/kg/sparqlparser/TestConfig.scala
This PR introduces the `DataFrameTyper` layer to the engine.  This PR also changes the RdfFormatter to make it able to reformat typed dataframes too.
=> Typed dataframes: add DataFrame typer

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala, modules/engine/src/main/scala/com/gsk/kg/engine/relational/relational.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/GraphSpec.scala
This PR fixed a bug where the graph variable column was being set to null when performing a union operation.
=> fixed bug where graph variables was being set to null on union operation

modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala, modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala, modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
This PR adds support for default and named graphs when using property paths expressions.
=> added support for default and named graphs to property paths

modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala, modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala, modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/PropertyPathRewrite.scala, modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala, modules/engine/src/main/scala/com/gsk/kg/engine/relational/relational.scala, modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala, modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
This PR adds integration tests of complex property paths, by combining some of the defined property paths.
It also fixes some minor bugs:
- Property path DAG rewrite when some property paths.
- Return duplicates triples on some corner cases.
=> Add complex property path test
